<?php

/**
 * @file
 * Contains forwardslash.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function forwardslash_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the forwardslash module.
    case 'help.page.forwardslash':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Example of a custom Drupal module built by Forwardslash Development Inc.') . '</p>';
      return $output;

    default:
  }
}
